name: windgraph
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=1.10
  - pytorch::torchvision
  - cudatoolkit=11.3
  - black
  - tqdm
  - pyyaml
  - matplotlib
  - networkx
  - streamlit
  - wandb
  - python-dotenv
  - pandas
  - pyyaml
  - more-itertools
  - plotly